# Generated by Django 2.2.5 on 2022-01-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20220114_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='room',
            field=models.ForeignKey(on_delete='cascade', related_name='photos', to='rooms.Room'),
        ),
    ]
