# Generated by Django 2.2.5 on 2022-01-14 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_auto_20220115_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='converstion', to=settings.AUTH_USER_MODEL),
        ),
    ]
